---

- hosts: localservers
  vars:
  remote_user: louis

  tasks:
    - name: update
      become: yes
      become_method: sudo      
      apt:
          update_cache: yes
          
    - name: upgrade
      become: yes
      become_method: sudo
      apt:
          upgrade: yes
