---
- name: Add ppa Repository
  become: yes
  apt_repository:
    repo: "ppa:ondrej/{{ php_ppa }}"
    update_cache: yes
    state: present

- name: Install php7.0-cli
  become: yes
  apt:
    pkg: php7.0-cli
    update_cache: yes
    cache_valid_time: 3600
    state: "{{ php_packages_state }}"

- name: Install php7.0-fpm
  become: yes
  apt:
    pkg: php7.0-fpm
    update_cache: yes
    cache_valid_time: 3600
    state: "{{ php_fpm_state }}"
  notify: restart php7.0-fpm

- name: Install PHP Packages
  become: yes
  apt:
    pkg: "{{ item }}"
    update_cache: yes
    cache_valid_time: 3600
    state: "{{ php_packages_state }}"
  with_items: "{{ php_packages }}"

- name: Install dev PHP Packages
  become: yes
  apt:
    pkg: "{{ item }}"
    update_cache: yes
    cache_valid_time: 3600
    state: "{{ php_packages_state }}"
  with_items: "{{ php_dev_packages }}"
  when: not ansidev_production

- name: Install production PHP Packages
  become: yes
  apt:
    pkg: "{{ item }}"
    update_cache: yes
    cache_valid_time: 3600
    state: "{{ php_packages_state }}"
  with_items: "{{ php_production_packages }}"
  when: ansidev_production

- name: Install xDebug
  become: yes
  apt:
    pkg: php-xdebug
    update_cache: yes
    cache_valid_time: 3600
    state: "{{ php_packages_state }}"
  when: "{{ php_xdebug }}"
